language: scala
scala:
#   - 2.10.7
   - 2.11.12
jdk: oraclejdk8
sudo: false
script: sbt clean +test
before_install:
  - echo "Running Setup Commands"
  - sudo apt-get update -qq
  # ---Setup sbt---
#  - curl --create-dirs -L -o $HOME/.sbt/launchers/1.2.1/sbt-launch.jar http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch-1.2.1.jar
  # ---Setup Thrift---
  # http://thrift.apache.org/docs/install/debian
  - sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  # http://archive.apache.org/dist/thrift/
  - wget http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3
  - ./configure --enable-libs=no --enable-tests=no --enable-tutorial=no --with-cpp=no --with-c_glib=no --with-java=yes --with-ruby=no --with-erlang=no --with-go=no --with-nodejs=no
  - sudo make install
  - cd ..
